#!/bin/sh

# Obtener el mensaje de commit del archivo
commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Define el patrón regex para los mensajes de commit permitidos
pattern="^(MINOR|MAJOR|BUGFIX)-.*$|^Merge.*$"

# Comprobar si el mensaje de commit coincide con el patrón
if ! echo "$commit_msg" | grep -qE "$pattern"; then
    echo "Error: Invalid commit message format. It must start with MINOR-, MAJOR-, BUGFIX-, or Merge (without -)."
    exit 1
fi
